package eu.icred.model.datatype.enumeration;


public enum DepositType {

NOT_AVAILABLE, CASH_BOND, PLEDGE, ASSIGNMENT_FOR_SECURITY, GUARANTEE, GUARANTEE_PAYMENT_INSURANCE, BANK_GUARANTEE, SAVINGS_LEASER, SAVINGS_OWNER, LOCAL_BANK, CASH_BANK_GUARANTEE, OTHER;
}